---
blueprint:
  name: "[AWTRIX] Multi-Device Battery Monitor"
  description: >
    Show battery levels of multiple devices on an AWTRIX clock.  
    Each device can have its own display text.  
    All results are combined into one message string.

    You can find all the icons [here](https://github.com/t3kmor/AWTRIXDeviceBatteryMonitor/tree/main/icons/).
    
    Requires a template sensor with the uptime of your Awtrix device in seconds (see *Last reported helper*).  
    Based on [this blueprint](https://flows.blueforcer.de/flow/XBJpOq0Zorzw).

  domain: automation
  input:
    enable_debug:
      name: Enable debug notification
      description: If enabled, a notification will show the intermediate values for debugging.
      default: false
      selector:
        boolean:
    awtrix:
      name: AWTRIX Device
      description: The AWTRIX device to send notifications to.
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: Blueforcer
              model: AWTRIX 3
    awtrix_last_reported:
      name: Last reported helper
      description: Template sensor that reports the uptime of your Awtrix in seconds.
      selector:
        entity:
          filter:
            - domain: sensor
    awtrix_matrix_entity:
      name: Matrix (screen) entity
      description: The entity that controls the Awtrix screen state.
      selector:
        entity:
          filter:
            - domain: light
    app_name:
      name: AWTRIX Application name
      description: Unique name for this custom app in AWTRIX MQTT.
      selector:
        text:
      default: multi_battery
    devices:
      name: Devices to monitor
      description: >
        Select one or more battery sensors.  
        The order must align with the labels you provide below.
      selector:
        entity:
          multiple: true
          filter:
            - integration: mobile_app
              device_class: battery
    labels:
      name: Labels for devices
      description: >
        Enter one label per line, in the same order as the devices.  
        Example:
        ```
        iPhone X
        iPad X
        iPhone Y
        Watch
        ```
      selector:
        text:
          multiline: true
    scroll_speed:
      name: Scroll speed
      description: Speed of text scrolling on the display (0–100%).
      default: 100
      selector:
        number:
          min: 0
          max: 100
          step: 10
          unit_of_measurement: "%"
          mode: slider
    duration:
      name: Duration (in seconds)
      description: How long the message is displayed on the Awtrix.
      default: "6"
    text_case:
      name: Text Case
      description: Choose how the message text is displayed.
      selector:
        select:
          options:
            - label: Use global setting
              value: "0"
            - label: Force Uppercase
              value: "1"
            - label: Show as you entered it
              value: "2"
      default: "2"
    push_icon:
      name: Icon Mode
      description: Defines how the icon behaves when the text scrolls.
      selector:
        select:
          options:
            - label: Icon doesn't move (default)
              value: "0"
            - label: Icon moves with text and will not appear again
              value: "1"
            - label: Icon moves with text but reappears with scrolling
              value: "2"
      default: "0"
mode: restart
variables:
  device_id: !input awtrix
  debug: !input enable_debug
  app: !input app_name
  awtrix: >
    {% if device_attr(device_id, 'name_by_user') is not none %}
      {{ device_attr(device_id, 'name_by_user') }}
    {% else %}
      {{ device_attr(device_id, 'name') }}
    {% endif %}
  devices: !input devices
  labels_raw: !input labels
  labels: >
    {{ labels_raw.split('\n') | map('trim') | reject('equalto','') | list }}
  push_icon: !input push_icon
  duration_on: !input duration
  text_case: !input text_case
  scroll_speed: !input scroll_speed
  payload: >-
    {%- set ns = namespace(text=[]) -%}
    {%- for i in range(devices|count) -%}
      {%- set sensor = devices[i] -%}
      {%- set label = labels[i] if labels|count > i else sensor -%}
      {%- set state = states(sensor) -%}
      {%- if state not in ['unknown','unavailable','none',''] -%}
        {%- set battery = state | int(0) -%}
        {%- set txt = label ~ ': ' ~ battery ~ '%' -%}
        {%- set ns.text = ns.text + [txt] -%}
      {%- endif -%}
    {%- endfor -%}
    {
      "icon":"battery",
      "text":"{{ ns.text | join('  |  ') }}",
      "pushIcon":{{push_icon}},
      "duration":{{duration_on}},
      "textCase":{{text_case}},
      "scrollSpeed":{{scroll_speed}}
    }

trigger:
  - platform: time_pattern
    minutes: /1

condition:
  - condition: numeric_state
    entity_id: !input awtrix_last_reported
    below: 20
  - condition: state
    entity_id: !input awtrix_matrix_entity
    state: 'on'

action:
  - if:
      - condition: template
        value_template: "{{ debug }}"
    then:
      - service: persistent_notification.create
        data:
          title: "AWTRIX Battery Debug"
          message: "{{payload}}"  
    else:
      - service: mqtt.publish
        data:
          qos: 0
          retain: false
          topic: "{{awtrix}}/custom/{{app}}"
          payload: "{{payload}}"
