blueprint:
  name: Certificate Expiration Pushover
  description: This automation blueprint notifies with a Pushover message when a SSL certificate is about
    to expire. See here https://pushover.net/api for more information.
  domain: automation
  input:
    certificate_input:
      name: Certificate
      description: The certificate timestamp
      selector:
        entity:
          integration: cert_expiry
    days_input:
      name: Days before
      description: Set how many days before expiration it should start sending notifications
      default: 5
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: days
          mode: slider
          step: 1.0
    time_input:
      name: Time
      description: What time of the day it should check and send the notification?
      default: '15:00'
      selector:
        time: {}
    target_input:
      name: Pushover Target
      description: What is the target to send the Pushover notification to?
      selector:
        text: {}
    sound_input:
      name: Pushover Sound
      description: What is the soundname of the Pushover notification?
      default: 'pianobar'
      selector:
        text: {}
    priority_input:
      name: Pushover Priority
      description: What is the priority of the Pushover notification?
      default: '0'
      selector:
        number:
          min: -2.0
          max: 2.0
          mode: slider
          step: 1.0
  source_url: https://github.com/Marck/home-assistant-blueprints/blob/main/certificate-expiration-pushover.yaml
trigger:
  platform: time
  at: !input 'time_input'
variables:
  days_var: !input 'days_input'
  certificate_var: !input 'certificate_input'
  expire_days_var: '{{ ((as_timestamp(states(certificate_var)) - as_timestamp(now()))
    / 60 / 60 / 24 ) | int }}'
condition:
  condition: template
  value_template: '{{ expire_days_var < days_var }}'
action:
- service: notify.pushover
  data:
    title: HASS SSL Certificate Expiration
    message: SSL cert is due to expire in {{ expire_days_var }} days
    target: !input 'target_input'
    data:
      sound: !input 'sound_input'
      priority: !input 'priority_input'
      retry: 30
      expire: 60
