blueprint:
  name: "Low battery detection for battery entities that runs at a specific interval"
  description: |
    Regularly test all sensors with 'battery' device-class for crossing a certain battery level threshold and if so execute an action.
    Example usecase: displaying the battery state every minute on a screen
  domain: automation
  input:
    threshold:
      name: Battery warning level threshold
      description: |
        Battery sensors below threshold are assumed to be low-battery 
        (as well as binary battery sensors with value 'on').
      default: 20
      selector:
        number:
          min: 5.0
          max: 100.0
          unit_of_measurement: '%'
          mode: slider
          step: 5.0
    interval:
      name: Interval in *minutes* to test on
      description: |
        Test is run at configured interval in minutes. 
        Use following format: `/minutes`, for example every minute: `/2`.
      default: '/2'
    optional_condition:
      name: (optional) Optional Template Condition
      description: >
        Optional template condition that must return true for automation to fire.
      default:
        - condition: template
          value_template: "true"
      selector:
        condition: {}
    exclude:
      name: Excluded Sensors
      description: |
        Battery sensors (e.g. smartphone) to exclude from detection. 
        Only entities and labels are supported, devices must be expanded!
      default:
        entity_id: []
      selector:
        target:
          entity:
            device_class: battery
    actions:
      name: Actions
      description: |
        Notifications or similar to be run. 
        {{sensors}} is replaced with the names 
        of the sensors being low on battery.
      selector:
        action: {}
  source_url: https://github.com/Marck/home-assistant-blueprints/blob/main/low-battery-level-detection-interval.yaml
variables:
  optional_condition_variable: !input 'optional_condition'
  threshold: !input 'threshold'
  exclude: !input 'exclude'
  exclude_entities: >
    {%- set ns = namespace(ret=[]) %}
    {%- for key in ['device', 'area', 'entity', 'label'] %}
      {%- set items = exclude.get(key ~ '_id', [])  %}
      {%- if items %}
        {%- set items = [ items ] if items is string else items %}
        {%- set items = items if key == 'entity' else items | map(key ~ '_entities') | sum(start=[]) %}
        {%- set ns.ret = ns.ret + [ items ] %}
      {%- endif %}
    {%- endfor %}
    {{ ns.ret | sum(start=[]) }}
  sensors: >
    {% set result = namespace(sensors=[]) %} 
    {% for state in states.sensor
      | rejectattr('attributes.device_class', 'undefined')
      | selectattr('attributes.device_class', '==', 'battery') %} 
      {% if 0 <= state.state | int(-1) < threshold | int 
        and not state.entity_id in exclude_entities
        and state.entity_id not in integration_entities("mobile_app") %}
        {% set result.sensors = result.sensors + [state.name ~ ' (' ~ state.state ~ '%)'] %}
      {% endif %}
    {% endfor %}
    {% for state in states.binary_sensor
      | rejectattr('attributes.device_class', 'undefined')
      | selectattr('attributes.device_class', '==', 'battery')
      | selectattr('state', '==', 'on') %}
      {% if not state.entity_id in exclude_entities %}
        {% set result.sensors = result.sensors + [state.name] %}
      {% endif %}
    {% endfor %}
    {{result.sensors|join('\n')}}
trigger:
- platform: time_pattern
  minutes: !input 'interval'
condition: []  
action:
  - if:
    - condition: template
      alias: Check if sensors variable is not empty.
      value_template: "{{ sensors != '''' }}"
    - condition: template
      alias: Check if optional condition returns true
      value_template: "{% if optional_condition_variable %}true{% endif %}"
    then: !input 'actions'
mode: single
