blueprint:
  name: Unavailable entity detection & notification
  description: Regularly test all entities' status to check for unavailability.
  domain: automation
  source_url: https://github.com/Marck/home-assistant-blueprints/blob/main/unavailable_entities_notification.yaml
  input:
    time:
      name: Time to test on
      description: Test is run at configured time
      default: '10:00:00'
      selector:
        time: {}
    monday_enabled:
      name: Monday
      description: Run test on Monday
      default: true
      selector:
        boolean: {}
    tuesday_enabled:
      name: Tuesday
      description: Run test on Tuesday
      default: true
      selector:
        boolean: {}
    wednesday_enabled:
      name: Wednesday
      description: Run test on Wednesday
      default: true
      selector:
        boolean: {}
    thursday_enabled:
      name: Thursday
      description: Run test on Thursday
      default: true
      selector:
        boolean: {}
    friday_enabled:
      name: Friday
      description: Run test on Friday
      default: true
      selector:
        boolean: {}
    saturday_enabled:
      name: Saturday
      description: Run test on Saturday
      default: true
      selector:
        boolean: {}
    sunday_enabled:
      name: Sunday
      description: Run test on Sunday
      default: true
      selector:
        boolean: {}
    exclude:
      name: Excluded Entities
      description: Entities (e.g. smartphone) to exclude from detection. Only entities and labels
        are supported, areas and devices must be expanded!
      default: {}
      selector:
        target: {}
    actions:
      name: Actions
      description: Notifications or similar to be run. {{entities}} is replaced with
        the names of unavailable entities.
      selector:
        action: {}
variables:
  monday_enabled: !input 'monday_enabled'
  tuesday_enabled: !input 'tuesday_enabled'
  wednesday_enabled: !input 'wednesday_enabled'
  thursday_enabled: !input 'thursday_enabled'
  friday_enabled: !input 'friday_enabled'
  saturday_enabled: !input 'saturday_enabled'
  sunday_enabled: !input 'sunday_enabled'
  current_day: '{{ now().weekday() | int }}'
  exclude: !input 'exclude'
  exclude_entities: >
     {%- set ns = namespace(ret=[]) %}
     {%- for key in ['device', 'area', 'entity', 'label'] %}
       {%- set items = exclude.get(key ~ '_id', [])  %}
       {%- if items %}
         {%- set items = [ items ] if items is string else items %}
         {%- set items = items if key == 'entity' else items | map(key ~ '_entities') | sum(start=[]) %}
         {%- set ns.ret = ns.ret + [ items ] %}
       {%- endif %}
     {%- endfor %}
     {{ ns.ret | sum(start=[]) }}
  entities: >
    {% set result = namespace(entities=[]) %}
      {% for state in states %}
        {% if exclude_entities is defined %}
          {% if state.state == 'unavailable' and not state.entity_id in exclude_entities %}
            {% set result.entities = result.entities + [state.name] %}
          {% endif %}
        {% else %}
          {% if state.state == 'unavailable' %}
            {% set result.entities = result.entities + [state.name] %}
          {% endif %}
        {% endif %}
      {% endfor %} 
    {{"⤵ \n-"}}
    {{result.entities|join('\n- ')}}
trigger:
- platform: time
  at: !input 'time'
condition:
- condition: template
  value_template: >
    {{ (current_day == 0 and monday_enabled) or
       (current_day == 1 and tuesday_enabled) or 
       (current_day == 2 and wednesday_enabled) or 
       (current_day == 3 and thursday_enabled) or 
       (current_day == 4 and friday_enabled) or
       (current_day == 5 and saturday_enabled) or
       (current_day == 6 and sunday_enabled) }}
- condition: template
  value_template: '{{ entities != "⤵ \n-"}}'
action:
- choose: []
  default: !input 'actions'
mode: single
max_exceeded: silent
